# Generated by Django 4.0.6 on 2022-08-14 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0007_country_alter_address_options_book_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
        migrations.RenameField(
            model_name='book',
            old_name='country',
            new_name='published_countriees',
        ),
    ]
