# Generated by Django 4.0.6 on 2022-08-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='admin_comment',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
